[tasks.dev]
workspace = false
install_crate = "cargo-watch"
command = "cargo"
args = ["watch", "-x", "clippy"]

[tasks.testw]
workspace = false
install_crate = "cargo-watch"
command = "cargo"
args = ["watch", "-x", "test -- --nocapture"]

[tasks.udeps]
workspace = false
install_crate = "udeps"
toolchain = "nightly"
command = "cargo"
args = ["udeps", "--all-targets"]

[tasks.format]
clear = true
workspace = false
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--all", "--", "--check"]

[tasks.clippy-z]
clear = true
workspace = false
install_crate = "cargo-clippy"
toolchain = "nightly"
command = "cargo"
args = ["clippy", "-Z", "unstable-options"]

[tasks.clippy]
workspace = false
install_crate = "cargo-clippy"
command = "cargo"
args = ["clippy"]

[tasks.clippy-pedantic]
workspace = false
install_crate = "cargo-clippy"
command = "cargo"
args = ["clippy", "--all", "--", "-D", "clippy::pedantic", "-D", "clippy::nursery", "-D", "warnings"]

[tasks.test]
workspace = false
command = "cargo"
args = ["test", "--lib", "--bins"]

[tasks.all]
workspace = false
dependencies = [
    "check",
    "format",
    "clippy",
    "test"
]